version: '3.8'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: rizqikevin
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: hospital_db
    ports:
      - "5433:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://rizqikevin:user123@localhost:5432/hospital_db"
      JWT_SECRET_KEY: "supersecretkey"
      GOOGLE_APPLICATION_CREDENTIALS: "/delman-viewer-367ebe359fdf.json"

